version: 0.2
phases:
  #install:
    #runtime-versions:
      #nodejs: 16
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.....
      - aws --version
      #- docker --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 660645611558.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=660645611558.dkr.ecr.us-east-2.amazonaws.com/wp-php
      #- IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      #- sudo systemctl start docker
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"phpwp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json

